services:
  mongodb:
    image: mongo:7.0
    container_name: inventorymanagement-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    depends_on:
      - mongodb

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_MONGODB_URI: mongodb://mongodb:27017/product-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      - mongodb
      - discovery-server

volumes:
  mongodb_data:
