server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://product-service:8080
          predicates:
            - Path=/api/product/**
        - id: order-service-route
          uri: http://order-service:8080
          predicates:
            - Path=/api/order/**
        - id: notification-service-route
          uri: http://notification-service:8080
          predicates:
            - Path=/api/notification/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

app:
  auth:
    username: ${APP_AUTH_USERNAME:admin}
    password: ${APP_AUTH_PASSWORD:password}
    secret: ${APP_AUTH_SECRET:change-this-secret-key-change-this-secret-key}
    expiration-ms: ${APP_AUTH_EXPIRATION_MS:3600000}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
